name: ReVanced Build Autosign

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build APKs
        run: ./build_revanced.sh

      - name: Create generic keystore for signing
        run: |
          keytool -genkey -v -keystore ./build/generic.keystore -alias generic -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"
          openssl base64 -A -in ./build/generic.keystore -out ./build/generic.keystore.base64
          echo "generic_keystore::$(cat ./build/generic.keystore.base64)" >> $GITHUB_ENV
        
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/
          signingKeyBase64: ${{ env.generic_keystore }}
          alias: "generic"
          keyStorePassword: "123456"
      
      - name: Set current date as env variable
        run: echo "date_now::$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Release Autosign ${{ env.date_now }}"
          files: |
            build/*.apk
            vanced-microG.apk
