name: ReVanced Build Autosign

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download Stored base APKs
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ github.repository }}
          tag: 'base'
          fileName: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build APKs
        run: ./build_revanced.sh

      - name: Create generic keystore for signing
        run: |
          keytool -genkey -v -keystore ./generic.keystore -alias generic -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"
          openssl base64 -A -in ./generic.keystore -out ./generic.keystore.base64
          echo "SIGNING_KEY_BASE64=$(cat ./generic.keystore.base64)" >> $GITHUB_ENV
          
      - name: Zipalign and Sign Android release
        run: |
          ./zipalign_sign.sh
        env:
          SIGNING_KEY_BASE64: ${{ env.SIGNING_KEY_BASE64 }}
          KEY_STORE_PASSWORD: 123456
      
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Release Autosign ${{ env.date_now }}"
          files: |
            build/*.apk
            vanced-microG.apk
