name: ReVanced Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Build APKs
        run: ./build_revanced.sh

      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "Release ${{ env.date_now }}"
          path: |
            build/*.apk
            vanced-microG.apk
          retention-days: 1
